[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.build]
cmds = [
  "npm install",
  "npx prisma generate",
  "npx prisma migrate deploy",
  "npm run build"
]

[phases.start]
cmd = "npm run start"
